config/routes.rb
Rails.application.routes.draw do
  root 'pictures#index'
  resources :pictures

  

  

end

app/models/picture.rb
class Picture < ActiveRecord::Base
	scope :newest_first, -> { order("created_at DESC")}
	scope :most_recent_five, -> { newest_first.limit(5)}
	scope :search_by_date, -> (date) {where("created_at < ?",date)}
end

#ここのscopeでmethodを作成。

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
	
	def index
		@newest_first = Picture.newest_first
		if params[:created_before]
			#ここのparamereで、ブラウザの日程を保存。
			mydate = Date.strptime(params[:created_before], "%Y-%m-%d")
			@created_before = Picture.search_by_date(mydate)# We made a method by scope.
		end #@created_beforeでobjyect保存
			#@created_beforeは、viewに渡される。
		@most_recent_five = Picture.most_recent_five


# one_single_picture = Picture.last
# an_array_of_pictures = Picture.where(something)
# @yoshis_pic = Picture.find(1)


	end


	def show 
		@picture = Picture.find(params[:id])
	end

	def new 
		@picture = Picture.new
	end

	def create 
		@picture = Picture.new(picture_params)
		if @picture.save 
			redirect_to pictures_url
		else
			render :new
		end
	end

	def edit 
		@picture = Picture.find(params[:id])
	end


	def destroy
		@picture = Picture.find(params[:id])
		@picture.destroy
		redirect_to pictures_url
	end


	def update 
		@picture = Picture.find(params[:id])

		if @picture.update_attributes(picture_params)
			redirect_to "/pictures/#{@picture.id}"
		else 
			render :edit
		end
	end

	
	def picture_params
		params.require(:picture).permit(:artist,:title,:url)
	end

end



# class PicturesController < ApplicationController
# 	def index
# 		@pictures = [
# 			{ 
# 				:title => "The old church on the coast white sea",
# 				:artist => "Sergey Ershv",
# 				:url => "http://bitmakerlabs.s3.amazonaws.com/photogur/house.jpg"
# 			},
# 			{  	:title => "Sea Power",
# 				:artist => "Sthepen Scullion",
# 				:url => "http://bitmakerlabs.s3.amazonaws.com/photogur/wave.jpg"
# 			},

# 			{ 	:title => "Intro the Poppies",
# 				:artist => "Jhon Whilhelm",
# 				:url => "http://bitmakerlabs.s3.amazonaws.com/photogur/girl.jpg"
# 			}
# 		]
# 	end


# def show
# 		@pictures = [
# 			{ 
# 				:title => "The old church on the coast white sea",
# 				:artist => "Sergey Ershv",
# 				:url => "http://bitmakerlabs.s3.amazonaws.com/photogur/house.jpg"
# 			},
# 			{  	:title => "Sea Power",
# 				:artist => "Sthepen Scullion",
# 				:url => "http://bitmakerlabs.s3.amazonaws.com/photogur/wave.jpg"
# 			},

# 			{ 	:title => "Intro the Poppies",
# 				:artist => "Jhon Whilhelm",
# 				:url => "http://bitmakerlabs.s3.amazonaws.com/photogur/girl.jpg"
# 			}
# 		]

# 		@picture = @pictures[params[:id].to_i]
# 	end

# 	def new
# 	end

# 	def create 
# 		render :text => "Saving a picture.URL: #{params[:url]}, Title: #{params[:title]}, Artist: #{params[:artist]}"
# 	end
# end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photogur</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pictures/edit.html.erb
<h1>Edit Picture</h1>	

<p>
	<%= link_to "Back", @picture %>
</p>

<%= form_for @picture do |f| %>
<p>
	<%= f.label "artist" %><br>
	<%= f.text_field "artist" %>
</p>
<p>
	<%= f.label "title" %><br>
	<%= f.text_field "title" %>
</p>
<p>
	<%= f.label "url" %><br>
	<%= f.text_field "url" %>
</p>
<p>
	<%= submit_tag "Save" %>
</p>
<% end %>

app/views/pictures/index.html.erb
<h1>Pictures</h1>
<%= link_to( "New Picture", new_picture_path, {class: "special"}) %> 

<h1>Most recent 5 picturces</h1>

<ul> 
	<% @most_recent_five.each do |picture| %>
	<li><%= picture.title %></li>
	<%= link_to image_tag(picture.url), "/pictures/#{picture.id}" %>
	<% end %>
</ul>

<h1>Newwest picture</h1>
<ul>
	<% @newest_first.each do |picture| %>
	<li><%= picture.title %></li>
	<%= link_to image_tag(picture.url), "/pictures/#{picture.id}" %>
	<% end %>
</ul>


<h1>Created_before</h1>
<%= link_to "Created before 2014 October","http://localhost:3000/?created_before=2014-11-08" %>
<ul>



	<% unless @created_before.nil? %>
	<p>The number is <%= @created_before.count %></p>
	<% @created_before.each do |picture| %>
	<li><% picture.title %></li>
	<%= link_to image_tag(picture.url), "/pictures/#{picture.id}" %>
	<% end %>
	<% else %>
	<p>Nothing</p>
	<% end %>
</ul>

app/views/pictures/new.html.erb
<h1>Add a picture</h1>
<%= link_to "Back to pictures" ,pictures_url %>

<%= form_for @picture do |f| %>


<p>
	<%= f.label "artist" %><br>
	<%= f.text_field "artist" %>
</p>
<p>
	<%= f.label "title" %><br>
	<%= f.text_field "title" %>
</p>
<p>
	<%= f.label "url" %><br>
	<%= f.text_field "url" %>
</p>
<p>
	<%= f.submit "Save" %>
</p>
<% end %>

app/views/pictures/show.html.erb
<%= link_to "Back to Pictures", pictures_url %>

<p><%= @picture.title %>, <% @picture.artist %></p>
<image_tag @picture.url %>

<%= link_to "Back to Pictures",pictures_url %> | <%= link_to "Edit" , edit_picture_path(@picture) %> | <%= link_to "Delete", @picture, method: :delete, data: {confirm: "Are you sure you want to delete thie picture?"} %>  